# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

validate_ <- function(path, embedded, version) {
    .Call('_kana_parser_validate_', PACKAGE = 'kana.parser', path, embedded, version)
}

